
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Neovim
      run: sudo apt-get install -y neovim

    - name: Cache Neovim plugins
      uses: actions/cache@v2
      with:
        path: ~/.local/share/nvim/site
        key: ${{ runner.os }}-neovim-plugins

    - name: Run tests
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
