
name: CI

on: [push, pull_request]

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    
    - name: Set up Lua
      uses: actions/setup-lua@v2
      with:
        lua-version: '5.4'
    
    - name: Run tests
      run: |
        # Add your test commands here
